// Vue/12_vue_pros/vue_test/14_路由/03_src_params参数/App.vue
<template>
  <div>
    <div class="row">
      <Header/>
    </div>
    <div class="row">
      <div class="col-xs-2 col-xs-offset-2">
        <div class="list-group">
          <router-link class="list-group-item" active-class="active" to="/about">About</router-link>
          <router-link class="list-group-item" active-class="active" to="/home">Home</router-link>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="panel">
          <div class="panel-body">
            <router-view></router-view>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import Header from '@/components/Header'
export default {
  name: "App",
  components: {
    Header
  }
}
</script>

// React/31_scaffold/10_src_first-level_routing/App.jsx
import React, {Component} from "react";
import {Redirect, Route, Switch} from "react-router-dom";
import About from "./pages/About/About";
import Home from "./pages/Home/Home";
import Header from "./components/header/Header";
import MyNavLink from "./components/MyNavLink";

export default class App extends Component {

    render() {
        return (
            <div>
                <div className="row">
                    <div className="col-xs-offset-2 col-xs-8">
                        <Header/>
                    </div>
                </div>
                <div className="row">
                    <div className="col-xs-2 col-xs-offset-2">
                        <div className="list-group">
                            <MyNavLink to="/about">About</MyNavLink>
                            <MyNavLink to="/home">Home</MyNavLink>
                        </div>
                    </div>
                    <div className="col-xs-6">
                        <div className="panel">
                            <div className="panel-body">
                                <Switch>
                                    <Route path="/about" element={<About/>}/>
                                    {/*exact 开启精准匹配, 但是会影响多级路由的使用, 能不用则不用*/}
                                    <Route exact={true} path="/home" element={<Home/>}/>
                                    <Redirect to="/home"/>
                                    {/*<Route path='*' element={<Navigate to='/home'/>}/>*/}
                                </Switch>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        )
    }
}
