// Vue/12_vue_pros/vue_test/src/components/Count.vue
<template>
  <div>
    <h1>当前求和为: {{$store.state.sum}}</h1>
    <select v-model="n">
      <option :value="1">1</option>
      <option :value="2">2</option>
      <option :value="3">3</option>
    </select>
    <button @click="increment">+</button>
    <button @click="decrement">-</button>
    <button @click="oddPlus">奇数加</button>
    <button @click="delayPlus">延迟加</button>
  </div>
</template>

<script>
export default {
  name: "Count",
  data(){
    return {
      n: 1 // 用户选择的数字
    }
  },
  methods: {
    increment(){
      this.$store.dispatch('increment', this.n)
    },
    decrement(){
      this.$store.dispatch('decrement', this.n)
    },
    oddPlus(){
      this.$store.dispatch('oddPlus', this.n)
    },
    delayPlus(){
      this.$store.dispatch('delayPlus', this.n)
    }
  }
}
</script>

<style scoped>
  button{
    margin-left: 5px;
  }
</style>

// React/41_redux/05_src_react-redux-basic/components/Count/index.jsx
import React, {Component} from 'react';

class Count extends Component {

    state = {};

    increment = () => {
        const {value} = this.selectNumber;
        this.props.increment(value * 1);
    }

    decrement = () => {
        const {value} = this.selectNumber;
        this.props.decrement(value * 1);
    }

    incrementIfOdd = () => {
        const {value} = this.selectNumber;
        if (this.props.count % 2 !== 0) {
            this.props.increment(value * 1);
        }
    }

    incrementAsync = () => {
        const {value} = this.selectNumber;
        this.props.ascnyIncrement(value * 1, 500);
    }

    render() {
        return (
            <div>
                <h1>当前数字为: {this.props.count}</h1>
                <select ref={c => this.selectNumber = c}>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                </select>&nbsp;
                <button onClick={this.increment}>+</button>
                &nbsp;
                <button onClick={this.decrement}>-</button>
                &nbsp;
                <button onClick={this.incrementIfOdd}>当前求和为奇数加</button>
                &nbsp;
                <button onClick={this.incrementAsync}>异步加</button>
            </div>
        );
    }
}

export default Count;
